package br.com.formbelar.view;

import br.com.formbelar.controller.FormController;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import java.sql.SQLException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HigorMedVet
 */
public class CadastroView extends javax.swing.JFrame {

    /**
     * Creates new form CadastroView
     */
    public CadastroView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Nome = new javax.swing.JLabel();
        lbl_Email = new javax.swing.JLabel();
        lbl_Senha = new javax.swing.JLabel();
        tf_Nome = new javax.swing.JTextField();
        tf_Email = new javax.swing.JTextField();
        tf_Senha = new javax.swing.JPasswordField();
        btn_Login = new javax.swing.JButton();
        btn_Cadastrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastrar uma nova conta");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Nome.setFont(new java.awt.Font("Gill Sans MT", 0, 16)); // NOI18N
        lbl_Nome.setForeground(new java.awt.Color(153, 153, 153));
        lbl_Nome.setText("Nome");
        getContentPane().add(lbl_Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 270, -1, -1));

        lbl_Email.setFont(new java.awt.Font("Gill Sans MT", 0, 16)); // NOI18N
        lbl_Email.setForeground(new java.awt.Color(153, 153, 153));
        lbl_Email.setText("Email");
        getContentPane().add(lbl_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 340, -1, -1));

        lbl_Senha.setFont(new java.awt.Font("Gill Sans MT", 0, 16)); // NOI18N
        lbl_Senha.setForeground(new java.awt.Color(153, 153, 153));
        lbl_Senha.setText("Senha");
        getContentPane().add(lbl_Senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 410, -1, -1));

        tf_Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_NomeActionPerformed(evt);
            }
        });
        getContentPane().add(tf_Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 260, 320, 40));

        tf_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_EmailActionPerformed(evt);
            }
        });
        getContentPane().add(tf_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 330, 320, 40));

        tf_Senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_SenhaActionPerformed(evt);
            }
        });
        getContentPane().add(tf_Senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 400, 320, 40));

        btn_Login.setContentAreaFilled(false);
        btn_Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LoginActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 580, 190, 30));

        btn_Cadastrar.setContentAreaFilled(false);
        btn_Cadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 490, 170, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cadastro.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tf_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_EmailActionPerformed

    private void tf_NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_NomeActionPerformed

    private void tf_SenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_SenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_SenhaActionPerformed

    private void btn_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LoginActionPerformed
        LoginView loginView = new LoginView ();
        this.dispose();
        loginView.setVisible(true);
    }//GEN-LAST:event_btn_LoginActionPerformed

    private void btn_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CadastrarActionPerformed
        try {
            FormController form = new FormController ();
            form.cadastrarUsuario(this);
        } catch (SQLException sql) {
            
        }
        
        LoginView loginView = new LoginView ();
        this.dispose();
        loginView.setVisible(true);
        
    }//GEN-LAST:event_btn_CadastrarActionPerformed

    // METODOS GETTER E SETTER
    
    
    
    public JTextField getTf_Email() {
        return tf_Email;
    }

    public void setTf_Email(JTextField tf_Email) {
        this.tf_Email = tf_Email;
    }

    public JTextField getTf_Nome() {
        return tf_Nome;
    }

    public void setTf_Nome(JTextField tf_Nome) {
        this.tf_Nome = tf_Nome;
    }

    public JPasswordField getTf_Senha() {
        return tf_Senha;
    }

    public void setTf_Senha(JPasswordField tf_Senha) {
        this.tf_Senha = tf_Senha;
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cadastrar;
    private javax.swing.JButton btn_Login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_Email;
    private javax.swing.JLabel lbl_Nome;
    private javax.swing.JLabel lbl_Senha;
    private javax.swing.JTextField tf_Email;
    private javax.swing.JTextField tf_Nome;
    private javax.swing.JPasswordField tf_Senha;
    // End of variables declaration//GEN-END:variables
}
